name: pub_stats_core
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.5
  json_annotation: ^4.4.0
  pub_api_client: ^2.2.0

dev_dependencies:
  rexios_lints: ^5.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
