name: pub_stats_core
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  pub_api_client:
    git:
      url: https://github.com/Rexios80/pub_api_client
      ref: 271038b5b5a4b19163f624f71df74f629f588d66

dev_dependencies:
  rexios_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
